//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sklad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Things
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Things()
        {
            this.Things1 = new HashSet<Things>();
            this.Things2 = new HashSet<Things>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string SerialNumber { get; set; }
        public System.DateTime ProduceDate { get; set; }
        public int InventoryNumb { get; set; }
        public int MeasureUnit { get; set; }
        public int Quantity { get; set; }
        public string FromWhere { get; set; }
        public string DocNumber { get; set; }
        public System.DateTime DocDate { get; set; }
        public int DocType { get; set; }
        public int ProdType { get; set; }
        public string WorkName { get; set; }
        public int Account { get; set; }
        public string PassportNumber { get; set; }
        public int Price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Things> Things1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Things> Things2 { get; set; }
    }
}
